/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[username]
      ,[password]
      ,[ten]
      ,[diachi]
      ,[email]
      ,[dienthoai]
      ,[role]
  FROM [online_book].[dbo].[admin]
